export const EQUIPAMENT = [
  { id: '1', label: 'BALANÇA' },
  { id: '2', label: 'FORNO' },
  { id: '3', label: 'MISTURADOR' },
  { id: '4', label: 'ESTEIRA TRANSPORTADORA' },
  { id: '5', label: 'MOINHO' },
  { id: '6', label: 'DOSADOR' },
  { id: '7', label: 'TANQUE DE MISTURA' },
  { id: '8', label: 'BOMBA DE CALOR' },
  { id: '9', label: 'CENTRIFUGA' },
  { id: '10', label: 'FILTRO PRENSA' },
  { id: '11', label: 'SECADOR' },
  { id: '12', label: 'GRANULADOR' },
  { id: '13', label: 'EMBALADEIRA' },
  { id: '14', label: 'PALETIZADORA' },
  { id: '15', label: 'SISTEMA DE REFRIGERAÇÃO' },
  { id: '16', label: 'CALDEIRA' },
  { id: '17', label: 'COMPRESSOR DE AR' },
  { id: '18', label: 'VENTILADOR' },
  { id: '19', label: 'EXAUSTOR' },
  { id: '20', label: 'SISTEMA DE CONTROLE' },
  { id: '21', label: 'SENSOR DE TEMPERATURA' },
  { id: '22', label: 'SENSOR DE PRESSÃO' },
  { id: '23', label: 'SENSOR DE NÍVEL' },
  { id: '24', label: 'VÁLVULA DE CONTROLE' },
  { id: '25', label: 'ATUADOR PNEUMÁTICO' },
  { id: '26', label: 'MOTOR ELÉTRICO' },
  { id: '27', label: 'REDUTOR DE VELOCIDADE' },
  { id: '28', label: 'ACOPLAMENTO' },
  { id: '29', label: 'CORREIA DE TRANSMISSÃO' },
  { id: '30', label: 'CORRENTE DE TRANSMISSÃO' },
  { id: '31', label: 'ROLAMENTO' },
  { id: '32', label: 'MANCAL' },
  { id: '33', label: 'VEDAÇÃO' },
  { id: '34', label: 'LUBRIFICADOR' },
  { id: '35', label: 'INSTRUMENTO DE MEDIÇÃO' },
  { id: '36', label: 'FERRAMENTA DE MANUTENÇÃO' },
  { id: '37', label: 'EPI - Equipamento de Proteção Individual' },
  { id: '38', label: 'EPC - Equipamento de Proteção Coletiva' },
  { id: '39', label: 'SOFTWARE DE GESTÃO' },
  { id: '40', label: 'SISTEMA DE SEGURANÇA' },
  { id: '41', label: 'ALARME' },
  { id: '42', label: 'DETECTOR DE FUMAÇA' },
  { id: '43', label: 'EXTINTOR DE INCÊNDIO' },
  { id: '44', label: 'PLACA DE SINALIZAÇÃO' },
  { id: '45', label: 'FITA DE DEMARCAÇÃO' },
  { id: '46', label: 'CADEADO DE SEGURANÇA' },
  { id: '47', label: 'GUARDA-CORPO' },
  { id: '48', label: 'PLATAFORMA DE ACESSO' },
  { id: '49', label: 'ESCADARIA' },
  { id: '50', label: 'CORRIMÃO' },
  { id: '51', label: 'ELEVADOR DE CARGA' },
  { id: '52', label: 'GUINDASTE' },
  { id: '53', label: 'TALHA' },
];
